global using AsteriskDotHMG.Common.Helpers;
global using AsteriskDotHMG.Common.Interfaces;
global using AsteriskDotHMG.Common.Methods;
global using AsteriskDotHMG.Common.Models;
global using AsteriskDotHMG.Notification.Interfaces;
global using AsteriskDotHMG.Notification.Models;
global using AsteriskDotHMG.Paging.Helpers;
global using AsteriskDotHMG.Storage.Interfaces;
global using AsteriskDotHMG.Storage.Models;
global using Azure;
global using Azure.Storage.Blobs;
global using Azure.Storage.Blobs.Models;
global using Azure.Storage.Queues;
global using Azure.Storage.Sas;
global using FluentValidation;
global using FluentValidation.Results;
global using MediatR;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.Azure.Functions.Worker;
global using Microsoft.Azure.Functions.Worker.Middleware;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Models;
global using Newtonsoft.Json;
global using SendGrid;
global using SendGrid.Helpers.Mail;
global using Swashbuckle.AspNetCore.Annotations;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using System.Collections;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq.Expressions;
global using System.Net;
global using System.Reflection;
global using System.Runtime.Serialization;
global using System.Text;
global using System.Text.RegularExpressions;
global using static AsteriskDotHMG.Common.Helpers.Enums;
global using AE = AsteriskDotHMG.Common.Helpers.ApplicationException;
global using VE = AsteriskDotHMG.Common.Helpers.ValidationException;
global using SM = AsteriskDotHMG.Storage.Models;
global using AM = Azure.Storage.Blobs.Models;
