global using AsteriskDotHMG.Common.Helpers;
global using AsteriskDotHMG.Common.Interfaces;
global using AsteriskDotHMG.Common.Methods;
global using AsteriskDotHMG.Notification.Interfaces;
global using AsteriskDotHMG.Notification.Models;
global using AsteriskDotHMG.Storage.Interfaces;
global using AsteriskDotHMG.Storage.Models;
global using Azure;
global using Azure.Storage.Blobs;
global using Azure.Storage.Blobs.Models;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Models;
global using Newtonsoft.Json;
global using SendGrid;
global using SendGrid.Helpers.Mail;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Net;
global using System.Reflection;
global using System.Text.RegularExpressions;
global using static AsteriskDotHMG.Common.Helpers.Enums;
global using SM = AsteriskDotHMG.Storage.Models;
global using AM = Azure.Storage.Blobs.Models;
